[package]
name = "rust_sha256_rsa_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2.workspace = true
rsa.workspace = true

[lints]
workspace = true

[[bin]]
name = "generate"
path = "src/main.rs"
