[package]
name = "p256"
type = "bin"
authors = [""]

[dependencies]
bignum = { tag = "v0.6.0", git = "https://github.com/noir-lang/noir-bignum" }
bigcurve = { tag = "v0.7.0", git = "https://github.com/noir-lang/noir_bigcurve" }
