[package]
name = "block-multiplier"
version = "0.1.0"
edition = "2024"

[dependencies]
seq-macro = "0.3.5"
fp-rounding = { path = "../fp-rounding" }

[dev-dependencies]
rand.workspace = true
divan.workspace = true
primitive-types = "0.13.1"

[[bench]]
name = "bench"
harness = false
