dg1 = [
    42,
    19,
    88,
    237,
    91,
    63,
    129,
    7,
    250,
    198,
    14,
    76,
    211,
    45,
    5,
    99,
    170,
    38,
    240,
    201,
    64,
    123,
    3,
    81,
    33,
    156,
    212,
    18,
    199,
    111,
    222,
    61,
    143,
    247,
    8,
    195,
    29,
    157,
    132,
    71,
    102,
    17,
    173,
    108,
    245,
    214,
    224,
    66,
    115,
    86,
    189,
    234,
    90,
    44,
    207,
    16,
    58,
    134,
    103,
    251,
    193,
    35,
    140,
    248,
    79,
    105,
    202,
    137,
    100,
    196,
    125,
    31,
    83,
    41,
    209,
    93,
    10,
    229,
    144,
    116,
    225,
    67,
    133,
    204,
    77,
    112,
    69,
    253,
    154,
    246,
    17,
    99,
    88,
    0,
    0,
]

dg1_offset_in_e_content = 0

# This is with the correct hash
e_content = [
    16,
    31,
    255,
    241,
    200,
    159,
    240,
    61,
    123,
    182,
    50,
    48,
    41,
    137,
    72,
    93,
    212,
    219,
    224,
    103,
    14,
    241,
    102,
    82,
    11,
    103,
    120,
    122,
    108,
    46,
    206,
    2,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
]

e_content_size = 64
signed_attributes_size = 32

# This is the correct one!
signed_attributes = [
    185,
    67,
    89,
    64,
    182,
    93,
    236,
    133,
    10,
    13,
    86,
    161,
    229,
    110,
    7,
    42,
    240,
    138,
    30,
    67,
    204,
    72,
    184,
    93,
    230,
    138,
    136,
    137,
    47,
    165,
    203,
    192,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
]

# --- Next: signature verification ---
dsc_pubkey = [
    178,
    222,
    65,
    145,
    183,
    197,
    0,
    103,
    183,
    145,
    106,
    183,
    76,
    170,
    55,
    13,
    91,
    81,
    0,
    211,
    84,
    73,
    3,
    95,
    14,
    53,
    253,
    81,
    48,
    139,
    36,
    182,
    15,
    44,
    162,
    142,
    231,
    72,
    131,
    20,
    194,
    5,
    172,
    20,
    166,
    63,
    228,
    93,
    112,
    106,
    187,
    122,
    14,
    6,
    178,
    185,
    70,
    99,
    46,
    222,
    239,
    247,
    172,
    100,
    254,
    17,
    12,
    128,
    86,
    131,
    33,
    93,
    170,
    149,
    249,
    102,
    181,
    4,
    117,
    0,
    216,
    172,
    140,
    76,
    71,
    77,
    253,
    255,
    250,
    241,
    75,
    143,
    217,
    253,
    105,
    61,
    112,
    174,
    2,
    255,
    204,
    178,
    153,
    111,
    165,
    212,
    41,
    35,
    44,
    241,
    87,
    90,
    246,
    219,
    48,
    39,
    3,
    159,
    128,
    113,
    242,
    66,
    138,
    234,
    173,
    16,
    40,
    10,
    252,
    63,
    8,
    65,
    36,
    94,
    102,
    73,
    63,
    137,
    189,
    2,
    135,
    122,
    129,
    236,
    195,
    101,
    191,
    189,
    124,
    161,
    182,
    62,
    36,
    19,
    54,
    202,
    186,
    136,
    157,
    69,
    167,
    59,
    79,
    149,
    232,
    72,
    95,
    62,
    93,
    167,
    72,
    201,
    33,
    119,
    149,
    162,
    208,
    222,
    34,
    27,
    178,
    228,
    188,
    75,
    214,
    232,
    212,
    248,
    75,
    112,
    99,
    127,
    205,
    152,
    70,
    185,
    17,
    38,
    12,
    104,
    83,
    43,
    65,
    170,
    25,
    76,
    71,
    134,
    53,
    73,
    230,
    79,
    195,
    10,
    223,
    218,
    236,
    245,
    153,
    81,
    82,
    185,
    109,
    143,
    71,
    81,
    5,
    116,
    54,
    114,
    150,
    1,
    129,
    108,
    145,
    99,
    212,
    193,
    254,
    82,
    241,
    180,
    49,
    173,
    162,
    52,
    87,
    24,
    221,
    119,
    46,
    150,
    59,
    131,
    138,
    201,
]

dsc_exponent = 65537

sod_signature = [
    32,
    232,
    9,
    91,
    243,
    211,
    190,
    99,
    192,
    96,
    134,
    62,
    2,
    44,
    223,
    116,
    100,
    153,
    141,
    47,
    65,
    22,
    212,
    219,
    48,
    153,
    147,
    83,
    134,
    176,
    138,
    30,
    222,
    149,
    209,
    246,
    48,
    26,
    24,
    12,
    234,
    129,
    193,
    109,
    183,
    190,
    181,
    18,
    0,
    67,
    40,
    7,
    156,
    223,
    124,
    231,
    116,
    172,
    45,
    157,
    134,
    239,
    32,
    126,
    150,
    215,
    36,
    209,
    105,
    115,
    174,
    114,
    162,
    223,
    141,
    194,
    34,
    203,
    87,
    122,
    158,
    236,
    119,
    24,
    75,
    127,
    182,
    39,
    197,
    90,
    86,
    29,
    114,
    131,
    191,
    241,
    124,
    74,
    211,
    158,
    205,
    234,
    166,
    46,
    59,
    6,
    176,
    32,
    164,
    42,
    254,
    139,
    93,
    72,
    124,
    144,
    111,
    157,
    36,
    99,
    38,
    204,
    5,
    83,
    63,
    141,
    89,
    142,
    219,
    216,
    68,
    236,
    16,
    11,
    22,
    165,
    86,
    140,
    47,
    54,
    142,
    233,
    28,
    82,
    147,
    240,
    196,
    110,
    134,
    100,
    103,
    245,
    105,
    185,
    68,
    208,
    93,
    7,
    11,
    15,
    69,
    244,
    38,
    99,
    221,
    82,
    153,
    125,
    198,
    165,
    121,
    228,
    144,
    70,
    1,
    97,
    251,
    208,
    144,
    68,
    170,
    226,
    232,
    191,
    42,
    138,
    232,
    33,
    80,
    42,
    70,
    241,
    125,
    37,
    243,
    199,
    93,
    46,
    171,
    75,
    87,
    243,
    205,
    138,
    100,
    252,
    145,
    241,
    120,
    161,
    100,
    44,
    120,
    182,
    59,
    55,
    3,
    219,
    86,
    113,
    10,
    232,
    21,
    98,
    135,
    207,
    114,
    175,
    252,
    222,
    194,
    86,
    212,
    36,
    123,
    163,
    17,
    50,
    105,
    211,
    186,
    207,
    7,
    166,
    36,
    202,
    86,
    221,
    82,
    44,
    232,
    244,
    127,
    253,
    37,
    49,
]

# This is just \mu = \lfloor b^{2k} / N \rfloor in Barrett reduction
dsc_pubkey_redc_param = [
    1,
    110,
    100,
    136,
    151,
    175,
    52,
    77,
    43,
    249,
    136,
    4,
    88,
    34,
    81,
    89,
    221,
    27,
    0,
    83,
    66,
    119,
    128,
    158,
    215,
    166,
    189,
    68,
    41,
    74,
    34,
    55,
    245,
    232,
    240,
    165,
    196,
    222,
    38,
    101,
    254,
    50,
    189,
    100,
    97,
    249,
    138,
    130,
    102,
    25,
    68,
    157,
    21,
    182,
    156,
    149,
    95,
    212,
    144,
    149,
    139,
    41,
    227,
    178,
    227,
    59,
    150,
    112,
    26,
    111,
    215,
    92,
    243,
    162,
    47,
    142,
    95,
    155,
    47,
    90,
    138,
    101,
    250,
    158,
    83,
    248,
    117,
    201,
    12,
    181,
    30,
    211,
    116,
    206,
    201,
    157,
    152,
    16,
    136,
    65,
    81,
    174,
    95,
    21,
    119,
    209,
    77,
    131,
    144,
    239,
    108,
    121,
    96,
    190,
    144,
    31,
    64,
    11,
    92,
    51,
    234,
    225,
    198,
    192,
    53,
    98,
    90,
    27,
    1,
    239,
    188,
    5,
    91,
    164,
    246,
    149,
    109,
    176,
    30,
    57,
    210,
    176,
    146,
    64,
    148,
    49,
    70,
    142,
    161,
    10,
    21,
    172,
    117,
    104,
    128,
    58,
    52,
    89,
    97,
    213,
    50,
    79,
    102,
    129,
    178,
    189,
    43,
    111,
    124,
    89,
    214,
    153,
    60,
    202,
    199,
    137,
    234,
    165,
    250,
    205,
    151,
    138,
    1,
    195,
    231,
    248,
    117,
    209,
    132,
    79,
    129,
    224,
    5,
    94,
    219,
    137,
    131,
    11,
    148,
    45,
    235,
    46,
    159,
    188,
    255,
    180,
    139,
    172,
    214,
    46,
    60,
    164,
    215,
    68,
    123,
    134,
    26,
    97,
    236,
    32,
    194,
    145,
    144,
    90,
    232,
    215,
    25,
    102,
    235,
    108,
    8,
    142,
    197,
    71,
    139,
    212,
    89,
    77,
    50,
    32,
    106,
    76,
    169,
    118,
    245,
    78,
    36,
    197,
    9,
    85,
    123,
    115,
    143,
    208,
    85,
    64,
    118,
]
