[package]
name = "ryan_write_test"
type = "bin"
authors = [""]
compiler_version = ">=0.22.0"

[dependencies]
# poseidon2 = { tag = "main", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon2" }
# noir_native_sha256 = { path = "../../noir-native-sha256" }
