[package]
name = "block-multiplier-sys"
version = "0.1.0"
edition = "2024"

[dependencies]
fp-rounding = { path = "../fp-rounding" }

[dev-dependencies]
rand.workspace = true
divan.workspace = true

[[bench]]
name = "montgomery_interleaved"
harness = false
